language: go
go:
- 1.6
install:
- go get github.com/gin-gonic/gin
deploy:
  provider: gae
  keyfile: service-account-key.json 
  project: openmunich17-api
before_install:
- openssl aes-256-cbc -K $encrypted_13ab883d087f_key -iv $encrypted_13ab883d087f_iv
  -in service-account-key.json.enc -out service-account-key.json -d
